import java.util.Random;
import java.util.Scanner;

class StudyAssistant {

    static Scanner sc = new Scanner(System.in);
        static Random r = new Random();

            public static void main(String[] args) {

                    String[] angry = {
                                    "Study properly you potato.",
                                                    "Even the fan is rotating faster than your progress.",
                                                                    "Bro opened the book just for decoration ☠️"
                                                                            };

                                                                                    String[] supportive = {
                                                                                                    "Its ok. One chapter at a time 😊",
                                                                                                                    "You survived this much already.",
                                                                                                                                    "Drink water and continue."
                                                                                                                                            };

                                                                                                                                                    int totalHours = 0;

                                                                                                                                                            System.out.println("===== STUDY ASSISTANT =====");

                                                                                                                                                                    while (true) {

                                                                                                                                                                                System.out.println("\n1. Study");
                                                                                                                                                                                            System.out.println("2. Check Progress");
                                                                                                                                                                                                        System.out.println("3. Exist dramatically");

                                                                                                                                                                                                                    int choice = sc.nextInt();

                                                                                                                                                                                                                                switch (choice) {

                                                                                                                                                                                                                                                case 1:

                                                                                                                                                                                                                                                                    System.out.println("How many hours did you study?");
                                                                                                                                                                                                                                                                                        int hrs = sc.nextInt();

                                                                                                                                                                                                                                                                                                            totalHours += hrs;

                                                                                                                                                                                                                                                                                                                                if (hrs <= 1) {
                                                                                                                                                                                                                                                                                                                                                        System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                        angry[r.nextInt(angry.length)]);
                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        supportive[r.nextInt(supportive.length)]);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (totalHours > 20) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        "Assistant: Are we preparing for JEE or escaping society?");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                case 2:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                "Total study hours: " + totalHours);

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    if (totalHours < 5) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Status: Academic goblin mode.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else if (totalHours < 15) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Status: Functioning student.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    else {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            "Status: Touch grass occasionally.");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    break;

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    case 3:

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Closing program...");
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.out.println(
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    "Remember: homework is temporary, suffering is recursive.");

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                        System.exit(0);
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                }